spring.application.name=cinema-backend

spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=CinemaBooking_Backlog;encrypt=false
spring.datasource.username=sa
spring.datasource.password=1
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect
